# just wait for PR to run on main as a tirgger
pr: none
trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.23.0
  pipelines:
    - pipeline: pr
      source: PR
      trigger:
        branches:
          include:
            - main

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    gitFetchDepth: 0
    skipGitTagging: true
    globalVariables:
      - template: .azure/pipelines/azure-pipelines-variables.yml@self
    validationJobs:
      - name: Docker Build Web
        steps:
          - template: ../steps/azure_web_app_docker_build_push.yml@templates
            parameters:
              azurecrName: $(azurecrName)
              dockerfilePath: $(Build.SourcesDirectory)/apps/web/Dockerfile
              repository: scheduling/web
              buildArgs:
                - GIT_SHA=$(Build.SourceVersion)
      - name: Function Build
        steps:
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: npm ci --omit=dev --workspace=inspector-programming-function --workspace=@pins/inspector-programming-database --workspace=@pins/inspector-programming-lib
              workingDirectory: $(Build.Repository.LocalPath)
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: npm run db-generate
              workingDirectory: $(Build.Repository.LocalPath)
          - script: |
              source ~/.bashrc
              # copy root node_modules to function (but don't overwrite)
              rsync -a -r --ignore-existing $(Build.Repository.LocalPath)/node_modules/ $(Build.Repository.LocalPath)/apps/function/node_modules/
              # ensure there is a @pins/inspector-programming-database folder
              mkdir -p $(Build.Repository.LocalPath)/apps/function/src/packages/inspector-programming-database
              # ensure there is a @pins/inspector-programming-lib folder
              mkdir -p $(Build.Repository.LocalPath)/apps/function/src/packages/inspector-programming-lib
              # copy db package to packages/inspector-programming-database folder
              cp -r $(Build.Repository.LocalPath)/packages/database/* $(Build.Repository.LocalPath)/apps/function/src/packages/inspector-programming-database/
              # copy db package to packages/inspector-programming-lib folder
              cp -r $(Build.Repository.LocalPath)/packages/lib/* $(Build.Repository.LocalPath)/apps/function/src/packages/inspector-programming-lib/
              # remove the package files to avoid subpath import issues - treat them as part of the functions code src
              rm $(Build.Repository.LocalPath)/apps/function/src/packages/inspector-programming-database/package.json
              rm $(Build.Repository.LocalPath)/apps/function/src/packages/inspector-programming-lib/package.json
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              # we do this after the above copy step so that the replacements can also apply to the packages themselves
              script: npm run prepare-package
              workingDirectory: $(Build.Repository.LocalPath)/apps/function
          - task: ArchiveFiles@2
            displayName: Archive files
            inputs:
              rootFolderOrFile: $(Build.Repository.LocalPath)/apps/function
              includeRootFolder: false
              archiveFile: $(System.DefaultWorkingDirectory)/functions.zip
          - publish: $(System.DefaultWorkingDirectory)/functions.zip
            artifact: integration-functions
            displayName: Publish Functions Artifact
