import { LPA_REGION_IDS } from './lpa-regions.js';

// generated content (using `fetch-lpas.ts), so no need to format only multiple lines
// prettier-ignore
export const LPAS_PROD = Object.freeze([
    {lpaCode: "Q9999", lpaName: "System Test Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "Q1111", lpaName: "System Test Borough Council 2", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "N5090", lpaName: "Barnet", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "H1705", lpaName: "Basingstoke and Deane Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "F0114", lpaName: "Bath and North East Somerset Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "V1260", lpaName: "Bournemouth, Christchurch and Poole", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "G5180", lpaName: "Bromley", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "K0425", lpaName: "Buckinghamshire Council - Wycombe Area", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "X3405", lpaName: "Cannock Chase District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "D0840", lpaName: "Cornwall Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "F1610", lpaName: "Cotswold District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "U4610", lpaName: "Coventry City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "J9497", lpaName: "Dartmoor National Park Authority", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "D1265", lpaName: "Dorset", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "C4615", lpaName: "Dudley Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "U1105", lpaName: "East Devon District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "B3410", lpaName: "East Staffordshire Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "W1715", lpaName: "Eastleigh Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "Y1110", lpaName: "Exeter City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "F9498", lpaName: "Exmoor National Park Authority", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "A1720", lpaName: "Fareham Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "P1615", lpaName: "Forest of Dean District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "U1620", lpaName: "Gloucester City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "T1600", lpaName: "Gloucestershire", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "J1725", lpaName: "Gosport", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "E5330", lpaName: "Greenwich", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "N1730", lpaName: "Hart District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "X1735", lpaName: "Havant Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "B5480", lpaName: "Havering", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "W1850", lpaName: "Herefordshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "P2114", lpaName: "Isle of Wight Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "K3415", lpaName: "Lichfield District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "J1860", lpaName: "Malvern Hills District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "Y1138", lpaName: "Mid Devon District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "B1740", lpaName: "New Forest District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "B9506", lpaName: "New Forest National Park Authority", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "P3420", lpaName: "Newcastle-under-Lyme Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "X1118", lpaName: "North Devon District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "R3705", lpaName: "North Warwickshire Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "W3710", lpaName: "Nuneaton and Bedworth Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "N1160", lpaName: "Plymouth City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "L5810", lpaName: "Richmond", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "E3715", lpaName: "Rugby Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "P1750", lpaName: "Rushmoor Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "L3245", lpaName: "Shropshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "J0350", lpaName: "Slough Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "Q4625", lpaName: "Solihull Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "Y9507", lpaName: "South Downs National Park Authority", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "K1128", lpaName: "South Hams District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "Q3115", lpaName: "South Oxfordshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "D1780", lpaName: "Southampton City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "Y3425", lpaName: "Stafford Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "B3438", lpaName: "Staffordshire Moorlands District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "J3720", lpaName: "Stratford-on-Avon District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "C1625", lpaName: "Stroud District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "U3935", lpaName: "Swindon Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "Z3445", lpaName: "Tamworth Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "P1133", lpaName: "Teignbridge District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "C3240", lpaName: "Telford and Wrekin Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "C1760", lpaName: "Test Valley Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "G1630", lpaName: "Tewkesbury Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "Z0835", lpaName: "The Isles of Scilly Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "X1165", lpaName: "Torbay Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "W1145", lpaName: "Torridge District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "V3120", lpaName: "Vale of White Horse District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "V4630", lpaName: "Walsall Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "T3725", lpaName: "Warwick District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "W0340", lpaName: "West Berkshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "Q1153", lpaName: "West Devon Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "D3125", lpaName: "West Oxfordshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "Y3940", lpaName: "Wiltshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "L1765", lpaName: "Winchester City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "D4635", lpaName: "Wolverhampton City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "M3835", lpaName: "Worthing Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "H1840", lpaName: "Wychavon District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "R1845", lpaName: "Wyre Forest District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "M1005", lpaName: "Amber Valley Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "W3005", lpaName: "Ashfield District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "D3505", lpaName: "Babergh District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "R4408", lpaName: "Barnsley Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "A3010", lpaName: "Bassetlaw District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "T2405", lpaName: "Blaby District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "M2372", lpaName: "Blackburn with Darwen Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "R1010", lpaName: "Bolsover District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "N4205", lpaName: "Bolton Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "Z2505", lpaName: "Boston Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "H1515", lpaName: "Brentwood Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "K2610", lpaName: "Broadland District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "E9505", lpaName: "Broads Authority", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "W1905", lpaName: "Borough of Broxbourne", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "J3015", lpaName: "Broxtowe Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "Z2315", lpaName: "Burnley Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "A4710", lpaName: "Calderdale Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "Q0505", lpaName: "Cambridge City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "E0535", lpaName: "Cambridgeshire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "M1520", lpaName: "Castle Point Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "X2410", lpaName: "Charnwood Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "A1015", lpaName: "Chesterfield Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "L3815", lpaName: "Chichester District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "M2515", lpaName: "City of Lincoln Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "F0935", lpaName: "Cumberland Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "A1910", lpaName: "Dacorum Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "N1350", lpaName: "Darlington Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "U1050", lpaName: "Derbyshire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "P1045", lpaName: "Derbyshire Dales District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "F4410", lpaName: "Doncaster Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "V0510", lpaName: "East Cambridgeshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "D2510", lpaName: "East Lindsey District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "J2285", lpaName: "Ebbsfleet Development Corporation", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "N1025", lpaName: "Erewash Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "Z1585", lpaName: "Essex County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "D0515", lpaName: "Fenland District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "M2325", lpaName: "Fylde Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "H4505", lpaName: "Gateshead Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "N3020", lpaName: "Gedling Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "K2230", lpaName: "Gravesham Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "U2615", lpaName: "Great Yarmouth Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "D0650", lpaName: "Halton Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "Q1770", lpaName: "Hampshire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "F2415", lpaName: "Harborough District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "N1540", lpaName: "Harlow District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "H0724", lpaName: "Hartlepool Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "B1415", lpaName: "Hastings Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "M1900", lpaName: "Hertfordshire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "N1920", lpaName: "Hertsmere Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "H1033", lpaName: "High Peak Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "K2420", lpaName: "Hinckley and Bosworth Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "H0520", lpaName: "Huntingdonshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "R2330", lpaName: "Hyndburn Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "R3515", lpaName: "Ipswich Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "W2275", lpaName: "Kent County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "V2004", lpaName: "Kingston-Upon-Hull City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "Z4718", lpaName: "Kirklees Metropolitan Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "V4305", lpaName: "Knowsley Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "Q9495", lpaName: "Lake District National Park", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "Q2371", lpaName: "Lancashire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "W2465", lpaName: "Leicester City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "Z5060", lpaName: "London Borough of Barking and Dagenham Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "R5510", lpaName: "London Borough of Hillingdon", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "N5660", lpaName: "London Borough of Lambeth", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "W5780", lpaName: "London Borough of Redbridge", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "X1545", lpaName: "Maldon District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "X3025", lpaName: "Mansfield District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "A2280", lpaName: "Medway Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "Y2430", lpaName: "Melton Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "D3830", lpaName: "Mid Sussex District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "W0734", lpaName: "Middlesbrough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "B3030", lpaName: "Newark & Sherwood District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "X2600", lpaName: "Norfolk County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "R1038", lpaName: "North East Derbyshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "B2002", lpaName: "North East Lincolnshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "X1925", lpaName: "North Hertfordshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "R2520", lpaName: "North Kesteven District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "Y2620", lpaName: "North Norfolk District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "W4515", lpaName: "North Tyneside Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "G2435", lpaName: "North West Leicestershire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "W9500", lpaName: "North York Moors National Park Authority", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "T9501", lpaName: "Northumberland National Park Authority", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "Q3060", lpaName: "Nottingham City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "L2440", lpaName: "Oadby and Wigston Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "F5730", lpaName: "Old Oak and Park Royal Development Corporation", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "U3100", lpaName: "Oxfordshire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "M9496", lpaName: "Peak District National Park Authority", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "E2340", lpaName: "Pendle Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "J0540", lpaName: "Peterborough City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "N2345", lpaName: "Preston City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "V0728", lpaName: "Redcar and Cleveland Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "T2350", lpaName: "Ribble Valley Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "B1550", lpaName: "Rochford District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "B2355", lpaName: "Rossendale Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "U1430", lpaName: "Rother District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "P4415", lpaName: "Rotherham Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "K5600", lpaName: "Royal Borough of Kensington and Chelsea", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "P3040", lpaName: "Rushcliffe Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "A2470", lpaName: "Rutland County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "M4320", lpaName: "Sefton Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "G2245", lpaName: "Sevenoaks District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "W0530", lpaName: "South Cambridgeshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "F1040", lpaName: "South Derbyshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "A2525", lpaName: "South Holland District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "E2530", lpaName: "South Kesteven District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "L2630", lpaName: "South Norfolk District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "F2360", lpaName: "South Ribble Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "A4520", lpaName: "South Tyneside Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "K1935", lpaName: "Stevenage Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "V3500", lpaName: "Suffolk County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "J4525", lpaName: "Sunderland City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "B3600", lpaName: "Surrey County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "V2255", lpaName: "Swale Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "P1560", lpaName: "Tendring District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "Z2260", lpaName: "Thanet District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "P1940", lpaName: "Three Rivers District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "M1595", lpaName: "Thurrock Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "H2265", lpaName: "Tonbridge and Malling Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "M2270", lpaName: "Tunbridge Wells Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "Y1945", lpaName: "Watford Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "C1950", lpaName: "Welwyn Hatfield Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "K0940", lpaName: "Westmorland and Furness Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "N2535", lpaName: "West Lindsey District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "F3545", lpaName: "West Suffolk", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "V4250", lpaName: "Wigan Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "W4325", lpaName: "Wirral Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "U2370", lpaName: "Wyre Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "C9499", lpaName: "Yorkshire Dales National Park Authority", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "Y3805", lpaName: "Adur District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "P4605", lpaName: "Birmingham City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "R0335", lpaName: "Bracknell Forest Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "Z0116", lpaName: "Bristol City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "B1605", lpaName: "Cheltenham Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "C3105", lpaName: "Cherwell District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "T1410", lpaName: "Eastbourne Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "M1710", lpaName: "East Hampshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "L2250", lpaName: "Folkestone and Hythe District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "P1425", lpaName: "Lewes District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "X5210", lpaName: "London Borough of Camden", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "F5540", lpaName: "London Borough of Hounslow", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "T5720", lpaName: "London Borough of Merton", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "A5840", lpaName: "London Borough of Southwark", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "P5870", lpaName: "London Borough of Sutton", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "H5960", lpaName: "London Borough of Wandsworth", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "Y0435", lpaName: "Milton Keynes Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "D0121", lpaName: "North Somerset Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "G3110", lpaName: "Oxford City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "Z1775", lpaName: "Portsmouth City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "E0345", lpaName: "Reading Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "Z5630", lpaName: "Royal Borough of Kingston Upon Thames", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "T0355", lpaName: "Royal Borough of Windsor and Maidenhead", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "G4620", lpaName: "Sandwell Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "P0119", lpaName: "South Gloucestershire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "C3430", lpaName: "South Staffordshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "M3455", lpaName: "Stoke-on-Trent City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "X0360", lpaName: "Wokingham Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "D1835", lpaName: "Worcester City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "C3810", lpaName: "Arun District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "E2205", lpaName: "Ashford Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "V1505", lpaName: "Basildon Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "K0235", lpaName: "Bedford Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "J2373", lpaName: "Blackpool Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "Z1510", lpaName: "Braintree District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "F2605", lpaName: "Breckland District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "Q1445", lpaName: "Brighton and Hove City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "P1805", lpaName: "Bromsgrove District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "C0440", lpaName: "Buckinghamshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "T4210", lpaName: "Bury Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "J2210", lpaName: "Canterbury City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "P0240", lpaName: "Central Bedfordshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "W1525", lpaName: "Chelmsford City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "R0660", lpaName: "Cheshire East Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "A0665", lpaName: "Cheshire West and Chester Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "D2320", lpaName: "Chorley Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "W4705", lpaName: "City of Bradford Metropolitan District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "K5030", lpaName: "City of London Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "X5990", lpaName: "City of Westminster Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "C2741", lpaName: "City of York Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "A1530", lpaName: "Colchester City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "Q3820", lpaName: "Crawley Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "T2215", lpaName: "Dartford Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "C1055", lpaName: "Derby City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "X2220", lpaName: "Dover District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "X1355", lpaName: "Durham County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "J1915", lpaName: "East Hertfordshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "E2001", lpaName: "East Riding of Yorkshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "X3540", lpaName: "East Suffolk Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "G1440", lpaName: "East Sussex County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "K3605", lpaName: "Elmbridge Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "J1535", lpaName: "Epping Forest District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "P3610", lpaName: "Epsom and Ewell Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "Y3615", lpaName: "Guildford Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "Z3825", lpaName: "Horsham District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "V2635", lpaName: "King's Lynn and West Norfolk Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "A2335", lpaName: "Lancaster City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "N4720", lpaName: "Leeds City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "M2460", lpaName: "Leicestershire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "Q2500", lpaName: "Lincolnshire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "Z4310", lpaName: "Liverpool City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "D5120", lpaName: "London Borough of Bexley", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "T5150", lpaName: "London Borough of Brent", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "L5240", lpaName: "London Borough of Croydon", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "A5270", lpaName: "London Borough of Ealing", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "Q5300", lpaName: "London Borough of Enfield", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "U5360", lpaName: "London Borough of Hackney", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "H5390", lpaName: "London Borough of Hammersmith and Fulham", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "Y5420", lpaName: "London Borough of Haringey", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "M5450", lpaName: "London Borough of Harrow", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "V5570", lpaName: "London Borough of Islington", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "C5690", lpaName: "London Borough of Lewisham", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "G5750", lpaName: "London Borough of Newham", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "E5900", lpaName: "London Borough of Tower Hamlets", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "B0230", lpaName: "Luton Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "U2235", lpaName: "Maidstone Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "B4215", lpaName: "Manchester City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "W3520", lpaName: "Mid Suffolk District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "C3620", lpaName: "Mole Valley District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "M4510", lpaName: "Newcastle Upon Tyne City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "Y2003", lpaName: "North Lincolnshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "M2840", lpaName: "North Northamptonshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "U2750", lpaName: "North Yorkshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "P2935", lpaName: "Northumberland County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "G2625", lpaName: "Norwich City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "L3055", lpaName: "Nottinghamshire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "W4223", lpaName: "Oldham Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "Q1825", lpaName: "Redditch Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "L3625", lpaName: "Reigate and Banstead Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "P4225", lpaName: "Rochdale Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "Q3630", lpaName: "Runnymede Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "U4230", lpaName: "Salford City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "J4423", lpaName: "Sheffield City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "E3335", lpaName: "Somerset Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "D1590", lpaName: "Southend-on-Sea Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "Z3635", lpaName: "Spelthorne Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "B1930", lpaName: "St Albans City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "H4315", lpaName: "St Helens Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "D3450", lpaName: "Staffordshire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "C4235", lpaName: "Stockport Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "H0738", lpaName: "Stockton-on-Tees Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "D3640", lpaName: "Surrey Heath Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "G4240", lpaName: "Tameside Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "M3645", lpaName: "Tandridge District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "Q4245", lpaName: "Trafford Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "C1570", lpaName: "Uttlesford District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "X4725", lpaName: "Wakefield Metropolitan District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "U5930", lpaName: "Waltham Forest London Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "M0655", lpaName: "Warrington Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "H3700", lpaName: "Warwickshire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "R3650", lpaName: "Waverley Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "C1435", lpaName: "Wealden District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "P2365", lpaName: "West Lancashire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "W2845", lpaName: "West Northamptonshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "P3800", lpaName: "West Sussex County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "A3655", lpaName: "Woking Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "E1855", lpaName: "Worcestershire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "F0745", lpaName: "Hartlepool Development Corporation", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "K0750", lpaName: "Middlesbrough Development Corporation", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "J1155 ", lpaName: "Devon County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
]);
