import { LPA_REGION_IDS } from './lpa-regions.js';

// generated content (using `fetch-lpas.ts`), so no need to format only multiple lines
// prettier-ignore
export const LPAS_PROD = Object.freeze([
    {lpaCode: "Q9999", onsCode: null, lpaName: "System Test Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "Q1111", onsCode: null, lpaName: "System Test Borough Council 2", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "N5090", onsCode: "E60000203", lpaName: "Barnet", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "H1705", onsCode: "E60000242", lpaName: "Basingstoke and Deane Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "F0114", onsCode: "E60000288", lpaName: "Bath and North East Somerset Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "V1260", onsCode: "E60000289", lpaName: "Bournemouth, Christchurch and Poole", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "G5180", onsCode: "E60000206", lpaName: "Bromley", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "K0425", onsCode: null, lpaName: "Buckinghamshire Council - Wycombe Area", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "X3405", onsCode: "E60000117", lpaName: "Cannock Chase District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "D0840", onsCode: "E60000291", lpaName: "Cornwall Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "F1610", onsCode: "E60000309", lpaName: "Cotswold District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "U4610", onsCode: "E60000131", lpaName: "Coventry City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "J9497", onsCode: "E60000318", lpaName: "Dartmoor National Park Authority", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "D1265", onsCode: "E60000292", lpaName: "Dorset", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "C4615", onsCode: "E60000132", lpaName: "Dudley Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "U1105", onsCode: "E60000300", lpaName: "East Devon District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "B3410", onsCode: "E60000118", lpaName: "East Staffordshire Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "W1715", onsCode: "E60000244", lpaName: "Eastleigh Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "Y1110", onsCode: "E60000301", lpaName: "Exeter City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "F9498", onsCode: "E60000319", lpaName: "Exmoor National Park Authority", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "A1720", onsCode: "E60000245", lpaName: "Fareham Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "P1615", onsCode: "E60000310", lpaName: "Forest of Dean District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "U1620", onsCode: "E60000311", lpaName: "Gloucester City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "T1600", onsCode: "E10000013", lpaName: "Gloucestershire", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "J1725", onsCode: "E60000246", lpaName: "Gosport", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "E5330", onsCode: "E60000210", lpaName: "Greenwich", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "N1730", onsCode: "E60000247", lpaName: "Hart District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "X1735", onsCode: "E60000248", lpaName: "Havant Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "B5480", onsCode: "E60000212", lpaName: "Havering", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "W1850", onsCode: "E60000113", lpaName: "Herefordshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "P2114", onsCode: "E60000223", lpaName: "Isle of Wight Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "K3415", onsCode: "E60000119", lpaName: "Lichfield District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "J1860", onsCode: "E60000138", lpaName: "Malvern Hills District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "Y1138", onsCode: "E60000302", lpaName: "Mid Devon District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "B1740", onsCode: "E60000249", lpaName: "New Forest District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "B9506", onsCode: "E60000321", lpaName: "New Forest National Park Authority", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "P3420", onsCode: "E60000120", lpaName: "Newcastle-under-Lyme Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "X1118", onsCode: "E60000303", lpaName: "North Devon District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "R3705", onsCode: "E60000125", lpaName: "North Warwickshire Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "W3710", onsCode: "E60000126", lpaName: "Nuneaton and Bedworth Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "N1160", onsCode: "E60000295", lpaName: "Plymouth City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "L5810", onsCode: "E60000218", lpaName: "Richmond", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "E3715", onsCode: "E60000127", lpaName: "Rugby Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "P1750", onsCode: "E60000250", lpaName: "Rushmoor Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "L3245", onsCode: "E60000114", lpaName: "Shropshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "J0350", onsCode: "E60000228", lpaName: "Slough Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "Q4625", onsCode: "E60000134", lpaName: "Solihull Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "Y9507", onsCode: "E60000325", lpaName: "South Downs National Park Authority", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "K1128", onsCode: "E60000304", lpaName: "South Hams District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "Q3115", onsCode: "E60000267", lpaName: "South Oxfordshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "D1780", onsCode: "E60000229", lpaName: "Southampton City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "Y3425", onsCode: "E60000122", lpaName: "Stafford Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "B3438", onsCode: "E60000123", lpaName: "Staffordshire Moorlands District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "J3720", onsCode: "E60000128", lpaName: "Stratford-on-Avon District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "C1625", onsCode: "E60000312", lpaName: "Stroud District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "U3935", onsCode: "E60000297", lpaName: "Swindon Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "Z3445", onsCode: "E60000124", lpaName: "Tamworth Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "P1133", onsCode: "E60000305", lpaName: "Teignbridge District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "C3240", onsCode: "E60000116", lpaName: "Telford and Wrekin Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "C1760", onsCode: "E60000251", lpaName: "Test Valley Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "G1630", onsCode: "E60000313", lpaName: "Tewkesbury Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "Z0835", onsCode: "E60000293", lpaName: "The Isles of Scilly Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "X1165", onsCode: "E60000298", lpaName: "Torbay Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "W1145", onsCode: "E60000306", lpaName: "Torridge District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "V3120", onsCode: "E60000268", lpaName: "Vale of White Horse District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "V4630", onsCode: "E60000135", lpaName: "Walsall Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "T3725", onsCode: "E60000129", lpaName: "Warwick District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "W0340", onsCode: "E60000230", lpaName: "West Berkshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "Q1153", onsCode: "E60000307", lpaName: "West Devon Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "D3125", onsCode: "E60000269", lpaName: "West Oxfordshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "Y3940", onsCode: "E60000299", lpaName: "Wiltshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "L1765", onsCode: "E60000252", lpaName: "Winchester City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "D4635", onsCode: "E60000136", lpaName: "Wolverhampton City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "M3835", onsCode: "E60000287", lpaName: "Worthing Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "H1840", onsCode: "E60000141", lpaName: "Wychavon District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "R1845", onsCode: "E60000142", lpaName: "Wyre Forest District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "M1005", onsCode: "E60000077", lpaName: "Amber Valley Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "W3005", onsCode: "E60000106", lpaName: "Ashfield District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "D3505", onsCode: "E60000183", lpaName: "Babergh District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "R4408", onsCode: "E60000064", lpaName: "Barnsley Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "A3010", onsCode: "E60000107", lpaName: "Bassetlaw District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "T2405", onsCode: "E60000085", lpaName: "Blaby District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "M2372", onsCode: "E60000013", lpaName: "Blackburn with Darwen Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "R1010", onsCode: "E60000078", lpaName: "Bolsover District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "N4205", onsCode: "E60000025", lpaName: "Bolton Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "Z2505", onsCode: "E60000092", lpaName: "Boston Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "H1515", onsCode: "E60000156", lpaName: "Brentwood Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "K2610", onsCode: "E60000177", lpaName: "Broadland District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "E9505", onsCode: "E60000326", lpaName: "Broads Authority", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "W1905", onsCode: "E60000166", lpaName: "Borough of Broxbourne", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "J3015", onsCode: "E60000108", lpaName: "Broxtowe Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "Z2315", onsCode: "E60000035", lpaName: "Burnley Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "A4710", onsCode: "E60000069", lpaName: "Calderdale Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "Q0505", onsCode: "E60000149", lpaName: "Cambridge City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "E0535", onsCode: "E10000003", lpaName: "Cambridgeshire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "M1520", onsCode: "E60000157", lpaName: "Castle Point Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "X2410", onsCode: "E60000086", lpaName: "Charnwood Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "A1015", onsCode: "E60000079", lpaName: "Chesterfield Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "L3815", onsCode: "E60000283", lpaName: "Chichester District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "M2515", onsCode: "E60000094", lpaName: "City of Lincoln Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "F0935", onsCode: "E60000334", lpaName: "Cumberland Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "A1910", onsCode: "E60000167", lpaName: "Dacorum Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "N1350", onsCode: "E60000002", lpaName: "Darlington Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "U1050", onsCode: "E10000007", lpaName: "Derbyshire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "P1045", onsCode: "E60000080", lpaName: "Derbyshire Dales District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "F4410", onsCode: "E60000065", lpaName: "Doncaster Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "V0510", onsCode: "E60000150", lpaName: "East Cambridgeshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "D2510", onsCode: "E60000093", lpaName: "East Lindsey District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "J2285", onsCode: "E60000328; E51000003", lpaName: "Ebbsfleet Development Corporation", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "N1025", onsCode: "E60000081", lpaName: "Erewash Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "Z1585", onsCode: "E10000012", lpaName: "Essex County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "D0515", onsCode: "E60000151", lpaName: "Fenland District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "M2325", onsCode: "E60000037", lpaName: "Fylde Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "H4505", onsCode: "E60000008", lpaName: "Gateshead Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "N3020", onsCode: "E60000109", lpaName: "Gedling Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "K2230", onsCode: "E60000258", lpaName: "Gravesham Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "U2615", onsCode: "E60000178", lpaName: "Great Yarmouth Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "D0650", onsCode: "E60000017", lpaName: "Halton Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "Q1770", onsCode: "E10000014", lpaName: "Hampshire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "F2415", onsCode: "E60000087", lpaName: "Harborough District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "N1540", onsCode: "E60000161", lpaName: "Harlow District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "H0724", onsCode: "E60000003", lpaName: "Hartlepool Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "B1415", onsCode: "E60000238", lpaName: "Hastings Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "M1900", onsCode: "E10000015", lpaName: "Hertfordshire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "N1920", onsCode: "E60000169", lpaName: "Hertsmere Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "H1033", onsCode: "E60000082", lpaName: "High Peak Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "K2420", onsCode: "E60000088", lpaName: "Hinckley and Bosworth Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "H0520", onsCode: "E60000152", lpaName: "Huntingdonshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "R2330", onsCode: "E60000038", lpaName: "Hyndburn Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "R3515", onsCode: "E60000185", lpaName: "Ipswich Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "W2275", onsCode: "E10000016", lpaName: "Kent County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "V2004", onsCode: "E60000053", lpaName: "Kingston-Upon-Hull City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "Z4718", onsCode: "E60000070", lpaName: "Kirklees Metropolitan Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "V4305", onsCode: "E60000047", lpaName: "Knowsley Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "Q9495", onsCode: "E60000320", lpaName: "Lake District National Park", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "Q2371", onsCode: "E10000017", lpaName: "Lancashire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "W2465", onsCode: "E60000074", lpaName: "Leicester City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "Z5060", onsCode: "E60000202", lpaName: "London Borough of Barking and Dagenham Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "R5510", onsCode: "E60000213", lpaName: "London Borough of Hillingdon", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "N5660", onsCode: "E60000195", lpaName: "London Borough of Lambeth", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "W5780", onsCode: "E60000217", lpaName: "London Borough of Redbridge", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "X1545", onsCode: "E60000162", lpaName: "Maldon District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "X3025", onsCode: "E60000110", lpaName: "Mansfield District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "A2280", onsCode: "E60000224", lpaName: "Medway Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "Y2430", onsCode: "E60000089", lpaName: "Melton Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "D3830", onsCode: "E60000286", lpaName: "Mid Sussex District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "W0734", onsCode: "E60000004", lpaName: "Middlesbrough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "B3030", onsCode: "E60000111", lpaName: "Newark & Sherwood District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "X2600", onsCode: "E10000020", lpaName: "Norfolk County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "R1038", onsCode: "E60000083", lpaName: "North East Derbyshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "B2002", onsCode: "E60000054", lpaName: "North East Lincolnshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "X1925", onsCode: "E60000170", lpaName: "North Hertfordshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "R2520", onsCode: "E60000095", lpaName: "North Kesteven District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "Y2620", onsCode: "E60000180", lpaName: "North Norfolk District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "W4515", onsCode: "E60000010", lpaName: "North Tyneside Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "G2435", onsCode: "E60000090", lpaName: "North West Leicestershire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "W9500", onsCode: "E60000322", lpaName: "North York Moors National Park Authority", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "T9501", onsCode: "E60000323", lpaName: "Northumberland National Park Authority", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "Q3060", onsCode: "E60000075", lpaName: "Nottingham City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "L2440", onsCode: "E60000091", lpaName: "Oadby and Wigston Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "F5730", onsCode: "E60000330;", lpaName: "Old Oak and Park Royal Development Corporation", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "U3100", onsCode: "E10000025", lpaName: "Oxfordshire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "M9496", onsCode: "E60000324", lpaName: "Peak District National Park Authority", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "E2340", onsCode: "E60000040", lpaName: "Pendle Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "J0540", onsCode: "E60000146", lpaName: "Peterborough City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "N2345", onsCode: "E60000041", lpaName: "Preston City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "V0728", onsCode: "E60000006", lpaName: "Redcar and Cleveland Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "T2350", onsCode: "E60000042", lpaName: "Ribble Valley Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "B1550", onsCode: "E60000163", lpaName: "Rochford District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "B2355", onsCode: "E60000043", lpaName: "Rossendale Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "U1430", onsCode: "E60000240", lpaName: "Rother District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "P4415", onsCode: "E60000066", lpaName: "Rotherham Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "K5600", onsCode: "E60000194", lpaName: "Royal Borough of Kensington and Chelsea", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "P3040", onsCode: "E60000112", lpaName: "Rushcliffe Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "A2470", onsCode: "E60000076", lpaName: "Rutland County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "M4320", onsCode: "E60000049", lpaName: "Sefton Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "G2245", onsCode: "E60000260", lpaName: "Sevenoaks District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "W0530", onsCode: "E60000153", lpaName: "South Cambridgeshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "F1040", onsCode: "E60000084", lpaName: "South Derbyshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "A2525", onsCode: "E60000096", lpaName: "South Holland District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "E2530", onsCode: "E60000097", lpaName: "South Kesteven District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "L2630", onsCode: "E60000182", lpaName: "South Norfolk District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "F2360", onsCode: "E60000044", lpaName: "South Ribble Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "A4520", onsCode: "E60000011", lpaName: "South Tyneside Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "K1935", onsCode: "E60000172", lpaName: "Stevenage Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "V3500", onsCode: "E10000029", lpaName: "Suffolk County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "J4525", onsCode: "E60000012", lpaName: "Sunderland City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "B3600", onsCode: "E10000030", lpaName: "Surrey County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "V2255", onsCode: "E60000261", lpaName: "Swale Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "P1560", onsCode: "E60000164", lpaName: "Tendring District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "Z2260", onsCode: "E60000262", lpaName: "Thanet District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "P1940", onsCode: "E60000173", lpaName: "Three Rivers District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "M1595", onsCode: "E60000148", lpaName: "Thurrock Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "H2265", onsCode: "E60000263", lpaName: "Tonbridge and Malling Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "M2270", onsCode: "E60000264", lpaName: "Tunbridge Wells Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "Y1945", onsCode: "E60000174", lpaName: "Watford Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "C1950", onsCode: "E60000175", lpaName: "Welwyn Hatfield Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "K0940", onsCode: "E60000335", lpaName: "Westmorland and Furness Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "N2535", onsCode: "E60000098", lpaName: "West Lindsey District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "F3545", onsCode: "E60000187", lpaName: "West Suffolk", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "V4250", onsCode: "E60000034", lpaName: "Wigan Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "W4325", onsCode: "E60000051", lpaName: "Wirral Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "U2370", onsCode: "E60000046", lpaName: "Wyre Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "C9499", onsCode: "E60000327", lpaName: "Yorkshire Dales National Park Authority", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "Y3805", onsCode: "E60000281", lpaName: "Adur District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "P4605", onsCode: "E60000130", lpaName: "Birmingham City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "R0335", onsCode: "E60000221", lpaName: "Bracknell Forest Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "Z0116", onsCode: "E60000290", lpaName: "Bristol City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "B1605", onsCode: "E60000308", lpaName: "Cheltenham Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "C3105", onsCode: "E60000265", lpaName: "Cherwell District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "T1410", onsCode: "E60000237", lpaName: "Eastbourne Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "M1710", onsCode: "E60000243", lpaName: "East Hampshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "L2250", onsCode: "E60000257", lpaName: "Folkestone and Hythe District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "P1425", onsCode: "E60000239", lpaName: "Lewes District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "X5210", onsCode: "E60000188", lpaName: "London Borough of Camden", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "F5540", onsCode: "E60000214", lpaName: "London Borough of Hounslow", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "T5720", onsCode: "E60000216", lpaName: "London Borough of Merton", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "A5840", onsCode: "E60000198", lpaName: "London Borough of Southwark", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "P5870", onsCode: "E60000219", lpaName: "London Borough of Sutton", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "H5960", onsCode: "E60000200", lpaName: "London Borough of Wandsworth", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "Y0435", onsCode: "E60000225", lpaName: "Milton Keynes Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "D0121", onsCode: "E60000294", lpaName: "North Somerset Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "G3110", onsCode: "E60000266", lpaName: "Oxford City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "Z1775", onsCode: "E60000226", lpaName: "Portsmouth City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "E0345", onsCode: "E60000227", lpaName: "Reading Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "Z5630", onsCode: "E60000215", lpaName: "Royal Borough of Kingston Upon Thames", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "T0355", onsCode: "E60000231", lpaName: "Royal Borough of Windsor and Maidenhead", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "G4620", onsCode: "E60000133", lpaName: "Sandwell Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "P0119", onsCode: "E60000296", lpaName: "South Gloucestershire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "C3430", onsCode: "E60000121", lpaName: "South Staffordshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "M3455", onsCode: "E60000115", lpaName: "Stoke-on-Trent City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "X0360", onsCode: "E60000232", lpaName: "Wokingham Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "D1835", onsCode: "E60000140", lpaName: "Worcester City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "C3810", onsCode: "E60000282", lpaName: "Arun District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "E2205", onsCode: "E60000253", lpaName: "Ashford Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "V1505", onsCode: "E60000154", lpaName: "Basildon Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "K0235", onsCode: "E60000143", lpaName: "Bedford Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "J2373", onsCode: "E60000014", lpaName: "Blackpool Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "Z1510", onsCode: "E60000155", lpaName: "Braintree District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "F2605", onsCode: "E60000176", lpaName: "Breckland District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "Q1445", onsCode: "E60000222", lpaName: "Brighton and Hove City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "P1805", onsCode: "E60000137", lpaName: "Bromsgrove District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "C0440", onsCode: "E60000331", lpaName: "Buckinghamshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } }},
    {lpaCode: "T4210", onsCode: "E60000026", lpaName: "Bury Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "J2210", onsCode: "E60000254", lpaName: "Canterbury City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "P0240", onsCode: "E60000144", lpaName: "Central Bedfordshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "W1525", onsCode: "E60000158", lpaName: "Chelmsford City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "R0660", onsCode: "E60000015", lpaName: "Cheshire East Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "A0665", onsCode: "E60000016", lpaName: "Cheshire West and Chester Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "D2320", onsCode: "E60000036", lpaName: "Chorley Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "W4705", onsCode: "E60000068", lpaName: "City of Bradford Metropolitan District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "K5030", onsCode: "E60000189", lpaName: "City of London Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "X5990", onsCode: "E60000201", lpaName: "City of Westminster Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "C2741", onsCode: "E60000056", lpaName: "City of York Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "A1530", onsCode: "E60000159", lpaName: "Colchester City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "Q3820", onsCode: "E60000284", lpaName: "Crawley Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "T2215", onsCode: "E60000255", lpaName: "Dartford Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "C1055", onsCode: "E60000073", lpaName: "Derby City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "X2220", onsCode: "E60000256", lpaName: "Dover District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "X1355", onsCode: "E60000001", lpaName: "Durham County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "J1915", onsCode: "E60000168", lpaName: "East Hertfordshire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "E2001", onsCode: "E60000052", lpaName: "East Riding of Yorkshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "X3540", onsCode: "E60000184", lpaName: "East Suffolk Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "G1440", onsCode: "E10000011", lpaName: "East Sussex County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "K3605", onsCode: "E60000270", lpaName: "Elmbridge Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "J1535", onsCode: "E60000160", lpaName: "Epping Forest District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "P3610", onsCode: "E60000271", lpaName: "Epsom and Ewell Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "Y3615", onsCode: "E60000272", lpaName: "Guildford Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "Z3825", onsCode: "E60000285", lpaName: "Horsham District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "V2635", onsCode: "E60000179", lpaName: "King's Lynn and West Norfolk Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "A2335", onsCode: "E60000039", lpaName: "Lancaster City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "N4720", onsCode: "E60000071", lpaName: "Leeds City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "M2460", onsCode: "E10000018", lpaName: "Leicestershire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "Q2500", onsCode: "E10000019", lpaName: "Lincolnshire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "Z4310", onsCode: "E60000048", lpaName: "Liverpool City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "D5120", onsCode: "E60000204", lpaName: "London Borough of Bexley", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "T5150", onsCode: "E60000205", lpaName: "London Borough of Brent", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "L5240", onsCode: "E60000207", lpaName: "London Borough of Croydon", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "A5270", onsCode: "E60000208", lpaName: "London Borough of Ealing", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "Q5300", onsCode: "E60000209", lpaName: "London Borough of Enfield", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "U5360", onsCode: "E60000190", lpaName: "London Borough of Hackney", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "H5390", onsCode: "E60000191", lpaName: "London Borough of Hammersmith and Fulham", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "Y5420", onsCode: "E60000192", lpaName: "London Borough of Haringey", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "M5450", onsCode: "E60000211", lpaName: "London Borough of Harrow", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "V5570", onsCode: "E60000193", lpaName: "London Borough of Islington", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "C5690", onsCode: "E60000196", lpaName: "London Borough of Lewisham", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "G5750", onsCode: "E60000197", lpaName: "London Borough of Newham", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "E5900", onsCode: "E60000199", lpaName: "London Borough of Tower Hamlets", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "B0230", onsCode: "E60000145", lpaName: "Luton Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "U2235", onsCode: "E60000259", lpaName: "Maidstone Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "B4215", onsCode: "E60000027", lpaName: "Manchester City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "W3520", onsCode: "E60000186", lpaName: "Mid Suffolk District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "C3620", onsCode: "E60000273", lpaName: "Mole Valley District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "M4510", onsCode: "E60000009", lpaName: "Newcastle Upon Tyne City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "Y2003", onsCode: "E60000055", lpaName: "North Lincolnshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "M2840", onsCode: "E60000332", lpaName: "North Northamptonshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "U2750", onsCode: "E60000336", lpaName: "North Yorkshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "P2935", onsCode: "E60000005", lpaName: "Northumberland County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "G2625", onsCode: "E60000181", lpaName: "Norwich City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "L3055", onsCode: "E10000024", lpaName: "Nottinghamshire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "W4223", onsCode: "E60000028", lpaName: "Oldham Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "Q1825", onsCode: "E60000139", lpaName: "Redditch Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
    {lpaCode: "L3625", onsCode: "E60000274", lpaName: "Reigate and Banstead Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "P4225", onsCode: "E60000029", lpaName: "Rochdale Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "Q3630", onsCode: "E60000275", lpaName: "Runnymede Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "U4230", onsCode: "E60000030", lpaName: "Salford City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "J4423", onsCode: "E60000067", lpaName: "Sheffield City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "E3335", onsCode: "E60000337", lpaName: "Somerset Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "D1590", onsCode: "E60000147", lpaName: "Southend-on-Sea Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "Z3635", onsCode: "E60000276", lpaName: "Spelthorne Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "B1930", onsCode: "E60000171", lpaName: "St Albans City Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "H4315", onsCode: "E60000050", lpaName: "St Helens Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "D3450", onsCode: "E10000028", lpaName: "Staffordshire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "C4235", onsCode: "E60000031", lpaName: "Stockport Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "H0738", onsCode: "E60000007", lpaName: "Stockton-on-Tees Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "D3640", onsCode: "E60000277", lpaName: "Surrey Heath Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "G4240", onsCode: "E60000032", lpaName: "Tameside Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "M3645", onsCode: "E60000278", lpaName: "Tandridge District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "Q4245", onsCode: "E60000033", lpaName: "Trafford Metropolitan Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "C1570", onsCode: "E60000165", lpaName: "Uttlesford District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } }},
    {lpaCode: "X4725", onsCode: "E60000072", lpaName: "Wakefield Metropolitan District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } }},
    {lpaCode: "U5930", onsCode: "E60000220", lpaName: "Waltham Forest London Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } }},
    {lpaCode: "M0655", onsCode: "E60000018", lpaName: "Warrington Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "H3700", onsCode: "E10000031", lpaName: "Warwickshire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "R3650", onsCode: "E60000279", lpaName: "Waverley Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "C1435", onsCode: "E60000241", lpaName: "Wealden District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } }},
    {lpaCode: "P2365", onsCode: "E60000045", lpaName: "West Lancashire District Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } }},
    {lpaCode: "W2845", onsCode: "E60000333", lpaName: "West Northamptonshire Council", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } }},
    {lpaCode: "P3800", onsCode: "E10000032", lpaName: "West Sussex County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } }},
    {lpaCode: "A3655", onsCode: "E60000280", lpaName: "Woking Borough Council", LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } }},
    {lpaCode: "E1855", onsCode: "E10000034", lpaName: "Worcestershire County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } }},
    {lpaCode: "F0745", onsCode: "E60000340", lpaName: "Hartlepool Development Corporation", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "K0750", onsCode: "E60000341", lpaName: "Middlesbrough Development Corporation", LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } }},
    {lpaCode: "J1155", lpaName: "Devon County Council", LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } }},
]);
