// packages/database/src/seed/lpa-regions.js
export const LPA_REGION_NAMES = Object.freeze({
	NORTH: 'North',
	EAST: 'East',
	WEST: 'West'
});

// Use stable GUIDs (generate once and commit)
export const LPA_REGION_IDS = Object.freeze({
	NORTH_1: 'e66f1b92-9806-4e47-9917-554cb74b4871',
	NORTH_2: 'd1e4efa0-27b4-4434-a7fa-4fcbe67435de',
	NORTH_3: '902ccebd-5a19-4399-b25c-b5cd092f2f81',
	NORTH_4: '0d6f1a0a-87d2-4a48-8d9a-2b2d0b8b9d11',

	EAST_1: '1a9f4b3b-6c7a-4a79-9da3-9b9b68ecb1a1',
	EAST_2: '2b7e9c2a-5d8b-4f7a-8ea4-3c1d9fe2c2b2',
	EAST_3: '3c8fad1c-4e9c-4b6b-9fb5-4d2e0af3d3c3',
	EAST_4: '4d9abe0d-3fad-4c5c-afc6-5e3f1b04e4d4',

	WEST_1: '5ea1cf1e-2cbe-4d4d-b0d7-6f402c15f5e5',
	WEST_2: '6fb2de2f-1dcf-4e3e-c1e8-70413d26a6f6',
	WEST_3: '70c3ed30-0ee0-4f2f-d2f9-81524e37b707',
	WEST_4: '81d4fc41-ff01-4020-e30a-92635f48c818'
});

const REGION_CONNECTION = Object.freeze({
	NORTH: { connectOrCreate: { where: { name: LPA_REGION_NAMES.NORTH }, create: { name: LPA_REGION_NAMES.NORTH } } },
	EAST: { connectOrCreate: { where: { name: LPA_REGION_NAMES.EAST }, create: { name: LPA_REGION_NAMES.EAST } } },
	WEST: { connectOrCreate: { where: { name: LPA_REGION_NAMES.WEST }, create: { name: LPA_REGION_NAMES.WEST } } }
});

/**
 * @type {import('@pins/inspector-programming-database/src/client').Prisma.LpaRegionCreateInput[]}
 */
export const LPA_REGIONS = Object.freeze([
	{ id: LPA_REGION_IDS.NORTH_1, LpaRegionName: REGION_CONNECTION.NORTH, number: 1 },
	{ id: LPA_REGION_IDS.NORTH_2, LpaRegionName: REGION_CONNECTION.NORTH, number: 2 },
	{ id: LPA_REGION_IDS.NORTH_3, LpaRegionName: REGION_CONNECTION.NORTH, number: 3 },
	{ id: LPA_REGION_IDS.NORTH_4, LpaRegionName: REGION_CONNECTION.NORTH, number: 4 },
	{ id: LPA_REGION_IDS.EAST_1, LpaRegionName: REGION_CONNECTION.EAST, number: 1 },
	{ id: LPA_REGION_IDS.EAST_2, LpaRegionName: REGION_CONNECTION.EAST, number: 2 },
	{ id: LPA_REGION_IDS.EAST_3, LpaRegionName: REGION_CONNECTION.EAST, number: 3 },
	{ id: LPA_REGION_IDS.EAST_4, LpaRegionName: REGION_CONNECTION.EAST, number: 4 },
	{ id: LPA_REGION_IDS.WEST_1, LpaRegionName: REGION_CONNECTION.WEST, number: 1 },
	{ id: LPA_REGION_IDS.WEST_2, LpaRegionName: REGION_CONNECTION.WEST, number: 2 },
	{ id: LPA_REGION_IDS.WEST_3, LpaRegionName: REGION_CONNECTION.WEST, number: 3 },
	{ id: LPA_REGION_IDS.WEST_4, LpaRegionName: REGION_CONNECTION.WEST, number: 4 }
]);

export const LPAS = Object.freeze([
	{ lpaCode: 'Y3805', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'M1005', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'C3810', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'W3005', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'E2205', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'D3505', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'R4408', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'V1505', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } } },
	{ lpaCode: 'H1705', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'A3010', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'F0114', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'K0235', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } } },
	{ lpaCode: 'P4605', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'T2405', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'M2372', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'J2373', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'R1010', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'N4205', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'Z2505', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'V1260', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'R0335', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'Z1510', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } } },
	{ lpaCode: 'F2605', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'H1515', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } } },
	{ lpaCode: 'Q1445', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'Z0116', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'K2610', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'E9505', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'P1805', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'W1905', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'J3015', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'C0440', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'P0430', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'Z2315', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'T4210', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'A4710', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } } },
	{ lpaCode: 'Q0505', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } } },
	{ lpaCode: 'E0535', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } } },
	{ lpaCode: 'X3405', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'J2210', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'M1520', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } } },
	{ lpaCode: 'P0240', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } } },
	{ lpaCode: 'X2410', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'W1525', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } } },
	{ lpaCode: 'B1605', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'C3105', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'R0660', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'A0665', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'A1015', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'L3815', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'D2320', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'W4705', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } } },
	{ lpaCode: 'M2515', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'K5030', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'C2741', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'A1530', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } } },
	{ lpaCode: 'D0840', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'F1610', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'U4610', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'Q3820', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'F0935', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'H0900', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'A1910', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'N1350', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'T2215', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'J9497', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'Y2810', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'C1055', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'U1050', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'P1045', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'J1155', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'F4410', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'D1265', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'X2220', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'C4615', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'X1355', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'V0510', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } } },
	{ lpaCode: 'U1105', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'M1710', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'J1915', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'D2510', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'E2001', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'B3410', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'X3540', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'G1440', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'T1410', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'W1715', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'K3605', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'J1535', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } } },
	{ lpaCode: 'P3610', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'N1025', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'Z1585', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } } },
	{ lpaCode: 'Y1110', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'F9498', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'A1720', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'D0515', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } } },
	{ lpaCode: 'L2250', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'P1615', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'M2325', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'H4505', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'N3020', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'U1620', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'T1600', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'J1725', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'K2230', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'U2615', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'G6100', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'Y3615', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'D0650', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'Q1770', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'F2415', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'N1540', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } } },
	{ lpaCode: 'N1730', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'H0724', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'F0745', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'B1415', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'X1735', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'W1850', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'M1900', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'N1920', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'H1033', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'K2420', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'Z3825', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'H0520', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } } },
	{ lpaCode: 'R2330', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'R3515', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'P2114', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'W2275', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'V2635', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'V2004', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'Z4718', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } } },
	{ lpaCode: 'V4305', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'Q9495', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'Q2371', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'A2335', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'N4720', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } } },
	{ lpaCode: 'W2465', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'M2460', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'P1425', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'K3415', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'Q2500', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'Z4310', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'Z5060', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'N5090', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'D5120', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'T5150', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } } },
	{ lpaCode: 'G5180', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'X5210', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } } },
	{ lpaCode: 'L5240', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'A5270', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } } },
	{ lpaCode: 'Q5300', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'U5360', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'H5390', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'Y5420', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'M5450', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } } },
	{ lpaCode: 'B5480', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'R5510', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'F5540', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'V5570', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'N5660', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'C5690', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'T5720', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'G5750', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'W5780', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'A5840', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'P5870', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'E5900', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'H5960', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'B0230', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } } },
	{ lpaCode: 'U2235', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'X1545', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } } },
	{ lpaCode: 'J1860', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'B4215', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'X3025', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'A2280', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'Y2430', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'Y1138', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'W3520', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'D3830', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'W0734', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'K0750', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'Y0435', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'C3620', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'B1740', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'B9506', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'B3030', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'M4510', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'P3420', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'X2600', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'X1118', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'R1038', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'B2002', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'X1925', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'R2520', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'Y2003', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'Y2620', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'M2840', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'D0121', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'W4515', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'R3705', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'G2435', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'W9500', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'U2750', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'V2825', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'P2935', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'T9501', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'G2625', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'Q3060', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'L3055', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'W3710', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'L2440', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'F5730', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'W4223', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'G3110', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'U3100', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'M9496', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'E2340', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'J0540', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } } },
	{ lpaCode: 'N1160', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'Z1775', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'N2345', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'E0345', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'V0728', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'Q1825', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'L3625', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'T2350', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'L5810', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'P4225', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'B1550', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } } },
	{ lpaCode: 'B2355', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'U1430', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'P4415', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'E5330', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'K5600', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'Z5630', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'T0355', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'E3715', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'Q3630', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'P3040', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'P1750', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'A2470', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'U4230', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'G4620', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'M4320', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'G2245', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'J4423', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'L3245', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'J0350', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'Q4625', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'E3335', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'W0530', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } } },
	{ lpaCode: 'F1040', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'Y9507', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'P0119', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'K1128', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'A2525', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'E2530', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'L2630', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'Q3115', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'F2360', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'C3430', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'A4520', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'D1780', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'D1590', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } } },
	{ lpaCode: 'Z3635', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'B1930', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'H4315', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'Y3425', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'D3450', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'B3438', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'K1935', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'C4235', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'H0738', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'M3455', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'J3720', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'C1625', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'V3500', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'J4525', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'B3600', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'D3640', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'V2255', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'U3935', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'G4240', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'Z3445', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'M3645', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'P1133', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'C3240', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'P1560', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } } },
	{ lpaCode: 'C1760', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'G1630', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'Z2260', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'Z0835', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'P1940', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'M1595', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } } },
	{ lpaCode: 'H2265', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'X1165', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'W1145', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'Q4245', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'M2270', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'C1570', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } } },
	{ lpaCode: 'V3120', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'X4725', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_4 } } },
	{ lpaCode: 'V4630', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'U5930', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'M0655', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'T3725', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'H3700', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'Y1945', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'R3650', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'C1435', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'C1950', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'W0340', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'Q1153', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'P2365', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'N2535', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'W2845', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'M9570', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } },
	{ lpaCode: 'D3125', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'F3545', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_4 } } },
	{ lpaCode: 'P3800', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'X5990', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'K0940', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'V4250', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'Y3940', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'L1765', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'W4325', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'A3655', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_3 } } },
	{ lpaCode: 'X0360', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'D4635', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'D1835', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'E1855', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'M3835', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'H1840', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_3 } } },
	{ lpaCode: 'U2370', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'R1845', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_4 } } },
	{ lpaCode: 'C9499', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	// Test Regions from cbos test data
	{ lpaCode: 'Q9999', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_1 } } },
	{ lpaCode: 'BASI', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_1 } } },
	{ lpaCode: 'WAVE', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_1 } } },
	{ lpaCode: 'BRIS', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_2 } } },
	{ lpaCode: 'DORS', LpaRegion: { connect: { id: LPA_REGION_IDS.EAST_2 } } },
	{ lpaCode: 'WILT', LpaRegion: { connect: { id: LPA_REGION_IDS.WEST_2 } } },
	{ lpaCode: 'MAID', LpaRegion: { connect: { id: LPA_REGION_IDS.NORTH_3 } } }
]);
