export const SPECIALISMS = Object.freeze([
	'General allocation',
	'Schedule 1',
	'Schedule 2',
	'Enforcement',
	'Housing orders',
	'Rights of way',
	'Shopping',
	'Gypsy',
	'Housing',
	'Access',
	'Advertisements',
	'Appearance design',
	'High hedges',
	'Historic heritage',
	'Listed building and enforcement',
	'Natural heritage',
	'Renewable energy/wind farms',
	'Roads and traffics',
	'Transport',
	'Tree preservation order',
	'Waste',
	'Water'
]);
